# Generated by Django 5.2.3 on 2025-07-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64)),
                ('post', models.CharField(blank=True, max_length=2000)),
                ('community', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uname', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='images.jpg', upload_to='')),
                ('name', models.CharField(max_length=64)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('dob', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=64)),
                ('year_studying_in', models.CharField(max_length=10)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('community', models.CharField(blank=True, default='GNDU, Amritsar', max_length=100)),
                ('website', models.CharField(blank=True, max_length=1000)),
                ('github', models.CharField(blank=True, max_length=1000)),
                ('linkedin', models.CharField(blank=True, max_length=1000)),
                ('instagram', models.CharField(blank=True, max_length=1000)),
                ('twiiter', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64)),
                ('follower', models.ManyToManyField(blank=True, to='first.person')),
            ],
        ),
    ]
