# Generated by Django 4.1.6 on 2024-10-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('tagline', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=64)),
                ('year_studying_in', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
