# Generated by Django 4.1.6 on 2024-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='college',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
