# Generated by Django 4.1.6 on 2024-10-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_person_college_alter_person_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_studying_in',
            field=models.CharField(max_length=10),
        ),
    ]
