# Generated by Django 4.1.6 on 2024-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_alter_person_year_studying_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='twiiter',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
