# Generated by Django 4.1.6 on 2024-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_person_github_person_instagram_person_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
