# Generated by Django 4.1.6 on 2024-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_person_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='imgage',
        ),
    ]
