# Generated by Django 4.1.6 on 2024-10-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_rename_img_person_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='imgage',
            new_name='image',
        ),
    ]
