# Generated by Django 4.1.6 on 2024-10-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_rename_imgage_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
