# Generated by Django 4.1.6 on 2024-10-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_blog_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=64)),
            ],
        ),
    ]
