# Generated by Django 4.1.6 on 2024-10-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
