# Generated by Django 4.1.6 on 2024-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_delete_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post',
        ),
        migrations.AddField(
            model_name='blog',
            name='community',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='community',
            field=models.CharField(blank=True, default='GNDU, Amritsar', max_length=100),
        ),
    ]
