# Generated by Django 4.1.6 on 2024-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_remove_blog_post_blog_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='community',
            field=models.CharField(default='GNDU, Amritsar', max_length=100),
        ),
    ]
