# Generated by Django 4.1.6 on 2024-10-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_alter_blog_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='community',
        ),
    ]
