# Generated by Django 4.1.6 on 2024-10-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_remove_blog_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='uname',
        ),
    ]
