# Generated by Django 4.1.6 on 2024-10-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_remove_blog_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='community',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='uname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
