# Generated by Django 4.1.6 on 2024-10-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_blog_community_blog_post_blog_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='images.png', upload_to=''),
        ),
    ]
